def create_preproc(edge_index, num_nodes: int, k: int) -> int:
    """Builds Preprocessing 
    """
    ...
def destroy_preproc(handle: int) -> None: ...
def sample(handle: int, m_per_graph: int, k: int): ...
def has_graphlets(handle: int) -> bool: ...
def get_preproc_info(handle: int) -> dict: ...
